apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv2
spec:
 storageClassName: fujitsu2
# persistentVolumeReclaimPolicy: Delete
 accessModes:
 - ReadWriteOnce
 capacity:
  storage: 5Gi
 hostPath:
  path: /bujji2
  type: DirectoryOrCreate
